run:
  concurrency: 4

linters-settings:
  golint:
      min-confidence: 0.9

  gocyclo:
      min-complexity: 15

linters:
  disable-all: true
  enable:
    - staticcheck
    - govet
    - ineffassign
    - golint
    - goimports
