approvals:
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      # a public zalando org member
      # (any org in here counts)
      - zalando
      - zalando-incubator
    # OR a collaborator of the repo
    collaborators: true
X-Zalando-Team: teapot
