apiVersion: v2
name: kube-ingress-aws-controller
description: A Helm chart for the Kubernetes Ingress AWS Controller
type: application
version: 0.1.0
appVersion: "v0.20"
home: https://github.com/zalando-incubator/kube-ingress-aws-controller
sources:
  - https://github.com/zalando-incubator/kube-ingress-aws-controller
keywords:
  - ingress
  - aws
  - alb
  - nlb
maintainers:
  - name: zalando-incubator
