name: ci
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v7
      with:
        go-version: "^1.27"
        check-latest: true
    - run: make deps
    - run: make test
    - run: make lint
    - run: goveralls -coverprofile=profile.cov -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
